feed/urls.py
from django.contrib import admin
from django.urls import path
from feed.views import *

app_name = 'feed'

urlpatterns = [
    path('<str:user>/', index, name='index'),
    path('<str:user>/createpost/', createpost, name='createpost'),
    path('<str:user>/viewpost/<int:post_id>/', viewpost, name='viewpost'),
    path('email/email/', sending_mails, name='email'),
    path('<str:user>/<int:post_id>/delete_post/', delete_post, name='delete_post')
]

market/urls.py
from django.contrib import admin
from django.urls import path, include
from market.views import initial_page

from django.conf import settings
from django.conf.urls.static import static


app_name = 'market'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', initial_page, name='initial_page'),
    
    # registering the urls from users_register app
    path('', include('users_register.urls')),

    # registering the urls from feed app
    path('', include('feed.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users_register/urls.py
from django.contrib import admin
from django.urls import path
from users_register.views import *
from django.urls import reverse

from django.conf import settings
from django.conf.urls.static import static

app_name = 'users_register'

urlpatterns = [
    path('register/', register_page, name='register_page'),
    path('<str:user>/personal_details/', personal_info_page, name='personal_info_page'),
    path('<str:user>/personal_details/update/', personal_info_update, name='personal_info_update'),
    path('login/', login_page, name='login_page'),
    path('logout/', logout_page, name='logout_page'),
    #path('<str:user>/', index_page, name='index_page'),
    path('<str:user>/friends/', friends_page, name='friends_page'),
    path('<str:user>/<str:data>/profile/', profile_page, name='profile_page'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feed/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class FeedPost(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200) # CharField is for limited text
    post_content = models.TextField() # TextField is for unlimited text
    created_date = models.DateTimeField(default=timezone.now)
    locations = models.ManyToManyField('PostLocation',blank=True)

    def __str__(self):
        return self.title
    
    def postid(self):
        return self.id

    def body_snippet(self):
        if len(self.post_content) > 150:
            return self.post_content[:150] + '.........'
        else:
            return self.post_content

class PostLocation(models.Model):
    post_location = models.CharField(max_length=200)

    def __str__(self):
        return self.post_location


class PostLikeData(models.Model):
    post = models.OneToOneField(FeedPost, on_delete=models.CASCADE, primary_key=True)
    likes = models.ManyToManyField(User, related_name='likes', blank=True)

    def __str__(self):
        return self.post.title
    
    def like_count(self):
        return self.likes.count()

feed/forms.py
from django import forms
from .models import FeedPost, PostLocation

class CreatePostForm(forms.ModelForm):
    class Meta:
        model = FeedPost
        fields = ['title', 'post_content', 'locations']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Title'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Content'}),
            'locations': forms.SelectMultiple(attrs={'class': 'form-control'}),
        }

feed/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .models import FeedPost, PostLikeData
from .forms import CreatePostForm
from users_register.models import MyProfile
from django.core.mail import send_mail


@login_required(login_url='users_register:login_page')
def index(request, **kwargs):
    if request.method == 'POST':
        if request.POST.get('like'):
            post_id = request.POST.get('like')
            post = PostLikeData.objects.get(post=post_id)
            post.likes.add(request.user)
        elif request.POST.get('unlike'):
            post_id = request.POST.get('unlike')
            post = PostLikeData.objects.get(post=post_id)
            post.likes.remove(request.user)  
        return redirect('feed:index', user=request.user)
    user_name = kwargs['user']
    feed_posts = FeedPost.objects.all().order_by('-created_date')
    profile_data = MyProfile.objects.all()
    likes_data = PostLikeData.objects.all()
    
    context = {
        'feed_posts': feed_posts,
        'user_id': user_name,
        'profile_data': profile_data,
        'likes_data': likes_data,
    }


    return render(request, 'feed/postfeed.html', context)

@login_required(login_url='users_register:login_page')
def createpost(request, user):
    if request.method == 'POST':
        form = CreatePostForm(request.POST)
        if form.is_valid():
            form = FeedPost.objects.create(
                author=request.user,
                title= form.cleaned_data['title'],
                post_content= form.cleaned_data['post_content'],
            )

            form.save()
            location = request.POST.getlist('locations')
            form.locations.set(location)
            PostLikeData.objects.create(post=form).save()
            return redirect('feed:index', user=user)
    if request.method == 'GET':
        form = CreatePostForm()
    return render(request, 'feed/createpost.html',{'form': form} )


def viewpost(request, user, post_id):
    post = FeedPost.objects.get(id=post_id)
    profile_data = MyProfile.objects.get(user=post.author)
    context = {
        'data': post,
        'user_id': user,
        'profile_data': profile_data,
    }
    return render(request, 'feed/viewpost.html', context)


def delete_post(request, user, post_id):
    post = FeedPost.objects.get(id=post_id)
    post.delete()
    return redirect('feed:index', user=user)

def sending_mails(request):
    if request.method == "POST":
        subject = request.POST['subject']
        message = request.POST['message']
        email_from = request.POST['email']
        recipient_list = request.POST['recipient_list']
        send_mail(subject, message, email_from, recipient_list)
        return redirect('feed:sending_mails')  
    return render(request, 'feed/sending_mails.html')
    

feed/templates/feed/createpost.html
{% extends "feed/postfeed.html" %}

{% block title %}
<title>New Post</title>
{% endblock title %}


{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h2>New Post</h2>
            </div>
            <form method="POST" class="post-form">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                    {% endfor %}
                </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary">Create Post</button>
            </form>
        </div>
    </div>


{% endblock content %}

feed/templates/feed/postfeed.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

{% extends 'market/base_page.html' %}

{% block title %}
<title>home</title>
{% endblock title %}

{% block site_name %}
<a class="navbar-brand" href="{% url 'users_register:profile_page' user=request.user data=request.user %}">
  <img src="{{request.user.myprofile.profile_photo.url}}" class="img-circle" height="60" width="60" alt="Profile">
</a>
  
{% endblock site_name %}


{% block user_register %}
<li class="nav-item col-sm-2">
    <a class="nav-link" href={% url 'users_register:logout_page'%}>Logout</a>
</li>
{% endblock user_register %}

{% block content %}

<div class="container-fluid">
  <div class="col-sm-3">
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal" onclick=location.href='{% url "feed:createpost" request.user %}'>Create Post</button>
  </div><br><br>
  <div class="col-sm-9">
    <h4><small>RECENT POSTS</small></h4>
    <hr>
    <vr class="col-sm-2"></vr>

    <div class="row">
      {% for data in feed_posts %}
        <div class="card">
          <div class="container-fluid">
            <div class="col-sm-2 text-center">
              {% for profile in profile_data %}
              {% if profile.user == data.author %}
              <a href="{% url 'users_register:profile_page' user=request.user data=data.author %}">
                <img src="{{profile.profile_photo.url}}" class="img-circle" height="65" width="65" alt="Profile">
              </a>
              {% endif %}
              {% endfor %}
            </div>

            <div class="col-sm-10">
              <a href={% url "feed:viewpost" request.user data.id %}>
                <h2>{{ data.title}}</h2>
              </a>
              <h5><span class="glyphicon glyphicon-time"></span> Post by <a href="{% url 'users_register:profile_page' user=request.user data=data.author %}">{{ data.author}}</a>, {{ data.created_date}}.</h5>
              {% for location in data.locations.all %}
              <h5><span class="label label-info">{{location}}</span></h5>
              {% endfor %}
              <br>
              <p>{{ data.body_snippet}}</p>
              <br>
              <form method="POST" action="{% url 'feed:index' request.user %}">
                {% csrf_token %}
                {% for like in likes_data %}
                {% if like.post.id == data.id %}
                {% if request.user in like.likes.all %}
                  <button type="submit" name="unlike" value="{{data.id}}" class="btn btn-danger btn-sm"><i class="fas fa-heart"></i> Unlike</button>
                {% else %}
                  <button type="submit" name="like" value="{{data.id}}" class="btn btn-primary btn-sm"><i class="fas fa-heart"></i> Like</button>
                {% endif %}
                <p>{{like.like_count}}</p>
                {% endif %}
                {% endfor %}
              </form>

              <div class="col-sm-2 align-right-corner">
                <button type="submit" class="btn btn-danger" data-toggle="modal" data-target="#myModal" onclick=location.href='{% url "feed:delete_post" request.user data.id %}'>Delete</button>
              </div>
            </div>
          </div>
        </div>
        <div class="col-sm-2">
          <hr>
        </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}  

feed/templates/feed/sending_mails.html
<form method="POST">
    <input type="text" name="name" placeholder="Name">
    <input type="text" name="email" placeholder="Email">
    <input type="submit" name="submit" value="Submit">
</form>

feed/templates/feed/viewpost.html
{% extends 'feed/postfeed.html' %}

{% block title %}
<title>{{data.title}}</title>
{% endblock title %}


{% block content %}
<div class="row">
    <hr><hr>
    <div class="col-sm-1"></div>
    <div class="card col-sm-10">
        <div class="container-fluid">
            <div class="col-sm-2 text-center">
                  <img src="{{profile_data.profile_photo.url}}" class="img-circle" height="65" width="65" alt="Profile">
            </div>

            <div class="col-sm-10">
                <a href={% url "feed:viewpost" request.user data.id %}>
                <h2>{{ data.title}}</h2>
                </a>
                <h5><span class="glyphicon glyphicon-time"></span> Post by {{ data.author}}, {{ data.created_date}}.</h5>
                {% for location in data.locations.all %}
                <h5><span class="label label-info">{{ location}}</span></h5>
                {% endfor %}
                <br><br>
                <p>{{ data.post_content}}</p>
                <br><br>                
            </div>
        </div>
    </div>
</div>
{% endblock %}