feed/urls.py
from django.contrib import admin
from django.urls import path
from feed.views import *

app_name = 'feed'

urlpatterns = [
    path('<str:user>/', index, name='index'),
    path('<str:user>/createpost/', createpost, name='createpost'),
    path('<str:user>/viewpost/<int:post_id>/', viewpost, name='viewpost'),
    path('email/email/', sending_mails, name='email'),
    path('<str:user>/<int:post_id>/delete_post/', delete_post, name='delete_post')
]

market/urls.py
from django.contrib import admin
from django.urls import path, include
from market.views import initial_page

from django.conf import settings
from django.conf.urls.static import static


app_name = 'market'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', initial_page, name='initial_page'),
    
    # registering the urls from users_register app
    path('', include('users_register.urls')),

    # registering the urls from feed app
    path('', include('feed.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users_register/urls.py
from django.contrib import admin
from django.urls import path
from users_register.views import *
from django.urls import reverse

from django.conf import settings
from django.conf.urls.static import static

app_name = 'users_register'

urlpatterns = [
    path('register/', register_page, name='register_page'),
    path('<str:user>/personal_details/', personal_info_page, name='personal_info_page'),
    path('<str:user>/personal_details/update/', personal_info_update, name='personal_info_update'),
    path('login/', login_page, name='login_page'),
    path('logout/', logout_page, name='logout_page'),
    #path('<str:user>/', index_page, name='index_page'),
    path('<str:user>/friends/', friends_page, name='friends_page'),
    path('<str:user>/<str:data>/profile/', profile_page, name='profile_page'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

market/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse


def initial_page(request):
    if request.user.is_authenticated:
        user = request.user
        return redirect('feed:index', user)
    return render(request, 'market/initial_page.html')

market/templates/market/base_page.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>


<head class="header">
  <nav class="navbar navbar-expand-lg bg-body-tertiary" style="background-color: #e3f2fd;" width="100%" height="40%">
    <div class="container-fluid">
      <a class="navbar-brand" href={% url "initial_page" %}>{% block site_name %}{% endblock %}</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item col-sm-3">
            <a class="nav-link active" aria-current="page" href={% url "initial_page" %}>Home</a>
          </li>
          <li class="nav-item col-sm-3">
            <a class="nav-link" href={% url 'users_register:friends_page' request.user %}>Friends</a>
          </li>
          <li class="nav-item col-sm-3">
            <a class="nav-link" href="#">Photos</a>
          </li>

          {% block user_register %}
          {% endblock %}
        </ul>
            <form class="d-flex flex-row-reverse" role="search">
            <button class="btn btn-outline-success" type="submit">Search</button>
            <input class="col-sm-4" type="search" placeholder="Search" aria-label="Search" type="submit">

            </form>
            
        
      </div>
    </div>
  </nav>
</head>

<body>
    <!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}
  {% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <style>
    /* Set height of the grid so .sidenav can be 100% (adjust if needed) */
    .row.content {height: 1500px}
    
    /* Set gray background color and 100% height */
    .sidenav {
      background-color: #f1f1f1;
      height: 100%;
    }
    
    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }
    
    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height: auto;} 
    }
  </style>
</head>
<body><hr>
{% block content %}
{% endblock %}


</body>


</html>


</body>

market/templates/market/initial_page.html
{% extends 'market/base_page.html' %}

{% block title %}
<title>Market</title>
{% endblock title %}

{% block site_name %}
Blogger's Place
{% endblock %}

{% block user_register %}
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle col-sm-3" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        Create User
    </a>
    <ul class="dropdown-menu col-sm-3">
        <li><a class="dropdown-item" href={% url 'users_register:login_page' %}>Login</a></li>
        <li><a class="dropdown-item" href={% url 'users_register:register_page' %}>Register</a></li>
        <li><hr class="dropdown-divider"></li>
        <li><a class="dropdown-item" href="#">Continue as Guest</a></li>
    </ul>
</li>

{% endblock user_register %}